version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: rest_api_db
      POSTGRES_USER: rest_api_user
      POSTGRES_PASSWORD: rest_api_password
    volumes:
      - db_data:/var/lib/postgresql/data/
